backend:
  name: git-gateway
  repo: house-of-giants/sheryl-glubok
media_folder: "static/images"
public_folder: "/images"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "Pages"
    label: "Pages"
    files:
      - label: "Home - About Section"
        name: "/"
        file: "src/content/home.yml"
        fields:
          - {label: "Column One Image", name: "column_one_img", widget: "image"}
          - {label: "Column Two Image", name: "column_two_img", widget: "image"}
          - {label: "Column Three Image", name: "column_three_img", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Button Label", name: "button_label", widget: "string"}
      - label: "About"
        name: "/about"
        file: "src/content/about.yml"
        fields:
          - {label: "Intro", name: "intro", widget: "markdown"}
          - {label: "Intro Image", name: "intro_image", widget: "image"}
          - {label: "Button Label", name: "button_label", required: false, widget: "string", default: "Contact Sheryl"}
          - {label: "Button Link", name: "button_link", required: false, widget: "string", default: "/contact"}
          - label: Stories
            name: "stories"
            widget: "list"
            fields:
              - {label: "Story Title", name: "story_title", widget: "string"}
              - {label: "Story Excerpt", name: "story_excerpt", widget: "markdown"}
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        dateFormat: "YYYY-MM-DD"
        format: "YYYY-MM-DD HH:mm"
      - {label: "Featured Image", name: "thumbnail", required: false, widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "film"
    label: "Films"
    folder: "src/films"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "film"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Vimeo Link", name: "vimeo_url", widget: "string", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Release Date", name: "release_date", widget: "string"}
      - {label: "Is this an anticipated release date?", name: "anticipated_release", widget: "boolean", default: false}
      - {label: "Runtime", name: "runtime", widget: "number", valueType: "float", required: false, default: 0}
      - {label: "Written By", name: "written_by", widget: "list", required: false, default: null}
      - {label: "Directed By", name: "directed_by", widget: "list", required: false, default: null}
      - {label: "Produced By", name: "produced_by", widget: "list", required: false, default: null}
      - {label: "Starring", name: "starring", widget: "list", required: false, default: null}
      - {label: "Poster", name: "poster", widget: "image", requred: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Awards"
        name: "awards"
        widget: "list"
        required: false
        default: null
        fields: 
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Link to external site", name: "logo_link", widget: "string", required: false, default: null}
      - label: "Team"
        name: "team"
        widget: "list"
        required: false
        default: null
        fields:
          - {label: "Member Name", name: "member_name", widget: "string"}
          - {label: "Member Title", name: "member_title", widget: "string", required: false}
          - {label: "Member Excerpt", name: "member_excerpt", widget: "text", required: false}
          - {label: "Member Headshot", name: "member_headshot", widget: "image", required: false}