backend:
  name: git-gateway
  repo: house-of-giants/sheryl-glubok
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "Pages"
    label: "Pages"
    files:
      - label: "Home - About Section"
        name: "/"
        file: "src/content/home.yml"
        fields:
          - {label: "Column One Image", name: "column_one_img", widget: "image"}
          - {label: "Column Two Image", name: "column_two_img", widget: "image"}
          - {label: "Column Three Image", name: "column_three_img", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Button Label", name: "button_label", widget: "string"}
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", required: false, widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "film"
    label: "Films"
    folder: "src/films"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "film"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Vimeo Link", name: "vimeo_url", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}